version: '3.8'

services:
  app:
    container_name: challenge
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
