name: main CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Create .env
      run: cp .env.example .env
      
    - name: Build docker images
      run: docker build -t challenge .
      
    - name: Run docker container
      run: docker run -d -p 3000:3000 --name=challenge challenge
      
    - name: Run tests
      run: docker exec -t challenge npm test
      
    - name: Clean up
      run: |
        docker stop challenge || true
        docker rm challenge || true
        docker rmi challenge || true
